spring:
  datasource:
    username: root
    password: test
    url: jdbc:mysql://localhost:3306/movies
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

project:
  poster: posters/

base:
  url: "http://localhost:8080"